POST http://localhost:3000/contact/
Content-type: application/json
{
    "first_name": "Bella",
    "last_name": "Andersson",
    "email": "bella.andersson@gmail.com",
    "personal_number": "950713-1405",
    "address": "Utvecklargatan 99",
    "zipcode": "111 22",
    "city": "Stockholm",
    "country": "Sweden",
}

### 
POST http://localhost:3000/contact/invalid-id
Content-type: application/json
{
    "first_name": "Bella",
    "last_name": "Andersson",
    "email": "bella.andersson@gmail.com",
    "personal_number": "950713-1405",
    "address": "Utvecklargatan 99",
    "zipcode": "111 22",
    "city": "Stockholm",
    "country": "Sweden",
}

### 

GET http://localhost:3000/contact

###

GET http://localhost:3000/contact/658434ec44dcf5c4da578347