POST http://localhost:3000/contact/invalid-id
Content-type: application/json
{
    "firstname": "Bella",
    "lastname": "Andersson",
    "email": "bella.andersson@gmail.com",
    "personalnumber": "950713-1405",
    "address": "Utvecklargatan 99",
    "zipCode": "111 22",
    "city": "Stockholm",
    "country": "Sweden",
}

### 

GET http://localhost:3000/contact

###

GET http://localhost:3000/contact/658434ec44dcf5c4da578347